---
title: "R Notebook"
output: html_notebook
---

# 1. Deces

```{r}
time_on_study_brut_deces = c()
pv_tos_brut_deces = c()
time_on_study_age_deces = c()
pv_tos_age_deces = c()
age_scale_brut_deces = c()
pv_as_brut_deces = c()
age_scale_genera_deces = c()
pv_as_genera_deces = c()

for(var in cox_univar_deces){
  cox1 = coxph(Surv(time_to_deces, deces) ~ data2[,var] , data = data2)
  cox2 = coxph(Surv(time_to_deces, deces) ~ data2[,var] + age0, data = data2)
  cox3 = coxph(Surv(age0,age_at_deces, deces) ~ data2[,var], data = data2)
  cox4 = coxph(Surv(age0,age_at_deces, deces) ~ data2[,var] + year_naiss_cat, data = data2)

time_on_study_brut_deces = c(time_on_study_brut_deces,summary(cox1)$coefficient[,2])
pv_tos_brut_deces = c(pv_tos_brut_deces,signif(summary(cox1)$coefficients[5],2))

time_on_study_age_deces = c(time_on_study_age_deces,summary(cox2)$coefficient[1,2])
pv_tos_age_deces = c(pv_tos_age_deces,signif(summary(cox2)$coefficients[1,5],2))

age_scale_brut_deces = c(age_scale_brut_deces,summary(cox3)$coefficient[,2])
pv_as_brut_deces = c(pv_as_brut_deces,signif(summary(cox3)$coefficients[5],2))

age_scale_genera_deces = c(age_scale_genera_deces,summary(cox4)$coefficient[1,2])
pv_as_genera_deces = c(pv_as_genera_deces,signif(summary(cox4)$coefficients[1,5],2))
}
```


```{r}
compare_methods_deces = data.frame("Name" = names_echotracking[which(echotracking %in% cox_univar_deces)], 
                             
                             "time_on_study_brut" = round(time_on_study_brut_deces,2),
                             "pv_tos_brut" = pv_tos_brut_deces,
                             "signif_tos_brut" = ifelse(pv_tos_brut_deces<=0.05,"*"," "),
                             
                             "time_on_study_age" = round(time_on_study_age_deces,2),
                             "pv_tos_age" = pv_tos_age_deces,
                             "signif_tos_age" = ifelse(pv_tos_age_deces<=0.05,"*"," "),
                             
                             "age_scale_brut" = round(age_scale_brut_deces,2),
                             "pv_as_brut" = pv_as_brut_deces,
                             "signif_as_brut" = ifelse(pv_as_brut_deces<=0.05,"*"," "),
                             
                             "age_scale_genera" = round(age_scale_genera_deces,2),
                             "pv_as_genera" = pv_as_genera_deces,
                             "signif_as_genera" = ifelse(pv_as_genera_deces<=0.05,"*"," ")
                             )
```


```{r}
rm(time_on_study_brut_deces)
rm(pv_tos_brut_deces)
rm(time_on_study_age_deces)
rm(pv_tos_age_deces)
rm(age_scale_brut_deces)
rm(pv_as_brut_deces)
rm(age_scale_genera_deces)
rm(pv_as_genera_deces)
```

```{r}
kable(compare_methods_deces, longtable = T, col.names = c(" ", "HR", "p"," ","HR","p"," ", "HR","p"," ","HR","p"," "), caption = "Comparison of time scales in Cox regression with Death as the outcome") %>% 
  kable_styling(bootstrap_options = "striped", full_width = T)  %>%
  add_header_above(c(" " = 1, "Univariate" = 3, "Age-adjusted" = 3, "Univariate" = 3, "Generation-adjusted" = 3)) %>%
   add_header_above(c(" " = 1, "Time on Study as time scale" = 6, "Age as time scale" = 6)) %>%
 kable_styling(latex_options = c("repeat_header"))
```


# 1. CHD

```{r}
time_on_study_brut_chd = c()
pv_tos_brut_chd = c()
time_on_study_age_chd = c()
pv_tos_age_chd = c()
age_scale_brut_chd = c()
pv_as_brut_chd = c()
age_scale_genera_chd = c()
pv_as_genera_chd = c()

for(var in cox_univar_chd){
  cox1 = coxph(Surv(time_to_chd, chd) ~ data2[,var] , data = data2)
  cox2 = coxph(Surv(time_to_chd, chd) ~ data2[,var] + age0, data = data2)
  cox3 = coxph(Surv(age0,age_at_chd, chd) ~ data2[,var], data = data2)
  cox4 = coxph(Surv(age0,age_at_chd, chd) ~ data2[,var] + year_naiss_cat, data = data2)

time_on_study_brut_chd = c(time_on_study_brut_chd,summary(cox1)$coefficient[,2])
pv_tos_brut_chd = c(pv_tos_brut_chd,signif(summary(cox1)$coefficients[5],2))

time_on_study_age_chd = c(time_on_study_age_chd,summary(cox2)$coefficient[1,2])
pv_tos_age_chd = c(pv_tos_age_chd,signif(summary(cox2)$coefficients[1,5],2))

age_scale_brut_chd = c(age_scale_brut_chd,summary(cox3)$coefficient[,2])
pv_as_brut_chd = c(pv_as_brut_chd,signif(summary(cox3)$coefficients[5],2))

age_scale_genera_chd = c(age_scale_genera_chd,summary(cox4)$coefficient[1,2])
pv_as_genera_chd = c(pv_as_genera_chd,signif(summary(cox4)$coefficients[1,5],2))
}
```


```{r}
compare_methods_chd = data.frame("Name" = names_echotracking[which(echotracking %in% cox_univar_chd)], 
                             
                             "time_on_study_brut" = round(time_on_study_brut_chd,2),
                             "pv_tos_brut" = pv_tos_brut_chd,
                             "signif_tos_brut" = ifelse(pv_tos_brut_chd<=0.05,"*"," "),
                             
                             "time_on_study_age" = round(time_on_study_age_chd,2),
                             "pv_tos_age" = pv_tos_age_chd,
                             "signif_tos_age" = ifelse(pv_tos_age_chd<=0.05,"*"," "),
                             
                             "age_scale_brut" = round(age_scale_brut_chd,2),
                             "pv_as_brut" = pv_as_brut_chd,
                             "signif_as_brut" = ifelse(pv_as_brut_chd<=0.05,"*"," "),
                             
                             "age_scale_genera" = round(age_scale_genera_chd,2),
                             "pv_as_genera" = pv_as_genera_chd,
                             "signif_as_genera" = ifelse(pv_as_genera_chd<=0.05,"*"," ")
                             )
```

```{r}
rm(time_on_study_brut_chd)
rm(pv_tos_brut_chd)
rm(time_on_study_age_chd)
rm(pv_tos_age_chd)
rm(age_scale_brut_chd)
rm(pv_as_brut_chd)
rm(age_scale_genera_chd)
rm(pv_as_genera_chd)
```


```{r}
kable(compare_methods_chd, longtable = T, col.names = c(" ", "HR", "p"," ","HR","p"," ", "HR","p"," ","HR","p"," "), caption = "Comparison of time scales in Cox regression with CHD as the outcome") %>% 
  kable_styling(bootstrap_options = "striped", full_width = T)  %>%
  add_header_above(c(" " = 1, "Univariate" = 3, "Age-adjusted" = 3, "Univariate" = 3, "Generation-adjusted" = 3)) %>%
   add_header_above(c(" " = 1, "Time on Study as time scale" = 6, "Age as time scale" = 6)) %>%
 kable_styling(latex_options = c("repeat_header"))
```


