---
title: "R Notebook"
output: html_notebook
---



# 1 Base de donnée
```{r}
data_cl_sj = data4_std[,c(var_ajust[-11],stiffness_anat,stiffness_dyna)]
```

```{r}
data_cl_sj$plaquesOUI = ifelse(data_cl_sj$plaques == 1,1,0)
mean_plaquesOUI = sum(data_cl_sj$plaquesOUI)/nrow(data_cl_sj)
sd_plaquesOUI = sqrt(mean_plaquesOUI*(1-mean_plaquesOUI))
data_cl_sj$plaques_OUI = (data_cl_sj$plaquesOUI - mean_plaquesOUI)/sd_plaquesOUI
data_cl_sj$plaquesNON = ifelse(data_cl_sj$plaques == 0,1,0)
mean_plaquesNON = sum(data_cl_sj$plaquesNON)/nrow(data_cl_sj)
sd_plaquesNON = sqrt(mean_plaquesNON*(1-mean_plaquesNON))
data_cl_sj$plaques_NON = (data_cl_sj$plaquesNON - mean_plaquesNON)/sd_plaquesNON
```


# 2 Kmeans 
## 2.1 avec plaques en factor
```{r}
d_cl1 = data_cl_sj[,c(stiffness_anat,stiffness_dyna)]
```

```{r}
km_sj = kmeans(d_cl1, centers = 5, nstart = 20, iter.max = 10)
```
```{r}
plot(km_sj$withinss, ylab=  "Within-cluster sum of squares", xlab = "Number of clusters", type = 'b')
```
```{r}
km3_sj = kmeans(d_cl1, centers = 3, nstart = 20, iter.max = 20)
table(km3_sj$cluster)
``` 

```{r}
data4_std$km3_sj = as.factor(km3_sj$cluster)
```
## 2.2 avec plaques en dummy variables centrées réduites (loi de bernouilli)

```{r}
d_cl2 = data_cl_sj[,c(stiffness_anat,stiffness_dyna,"plaquesOUI","plaquesNON")]
d_cl2$plaques = NULL
```

```{r}
km3_sj_dummy = kmeans(d_cl2, centers = 3, nstart = 20, iter.max = 10)
table(km3_sj_dummy$cluster)
```
```{r}
data_cl_sj$km3 = km3_sj_dummy$cluster
data4$km3 = km3_sj_dummy$cluster
data4_std$km3 = km3_sj_dummy$cluster
data4_std$km3 =factor(data4_std$km3)
```
```{r}
ggsurvplot(surv_fit(Surv(time_to_deces, deces) ~ factor(km3), data = data4), ylim = c(0.92,1),conf.int = TRUE, risk.table = TRUE, pval = TRUE, censor.shape = "|")
ggsurvplot(surv_fit(Surv(time_to_chd, chd) ~ factor(km3), data = data4), ylim = c(0.92,1),conf.int = TRUE, risk.table = TRUE, pval = TRUE, censor.shape = "|")
ggsurvplot(surv_fit(Surv(time_to_stroke, stroke) ~ factor(km3), data = data4),conf.int = TRUE, risk.table = TRUE, pval = TRUE, censor.shape = "|")
```


```{r}
paste0(c(stiffness_anat,stiffness_dyna), collapse = "+")
```

```{r}
desc_var_ajust = compareGroups(km3 ~ age0+sexe+qm16+qm10+diab+bio10+bmi+ldl+trb17+mbp, data = data4)
createTable(desc_var_ajust, type = 1)
```

```{r}
export2latex(createTable(desc_var_ajust, type = 1))
```

```{r}
desc_param = compareGroups(km3 ~ imt+diam_bm+plaques+compli+wcsa+cws+stiffness+logyoung+coeffDist+distension+dist_rate_moy+pwvloc2+dploc, data = data4)
createTable(desc_param, type = 1)
```

```{r}
export2latex(createTable(desc_param, type = 1))
```
```{r}
test_deces = coxph(Surv(time_to_deces,deces) ~age0+sexe+qm16+qm10+diab+bio10+bmi+ldl+trb17+mbp+km3,data=data4_std)
```

```{r}
summary(test_deces)
```
```{r}
test_chd = coxph(Surv(time_to_chd,chd) ~age0+sexe+qm16+qm10+diab+bio10+bmi+ldl+trb17+mbp+km3,data=data4_std)
```

```{r}
summary(test_chd)
```

```{r}
test_stroke = coxph(Surv(time_to_stroke,stroke) ~age0+sexe+qm16+qm10+diab+bio10+bmi+ldl+trb17+mbp+km3,data=data4_std)
```

```{r}
summary(test_stroke)
```

# 3 EM

```{r}
em = Mclust(d_cl2, G = 3)
```


```{r}
table(em$classification)
```
```{r}
data4_std$em3 = em$classification
```


```{r}
chisq.test(data4_std$km3_sj,data4_std$em3)
```



# 4 CAH 


```{r}
res.pca = PCA(data_cl_sj, graph = F)
```


```{r}
res.HCPC = HCPC(res.pca, graph = F)
```

```{r}
plot(res.HCPC,choice = "3D.map")
```
```{r}
fviz_dend(res.HCPC, show_labels = FALSE)
```


```{r}
plot_grid(
fviz_cluster(km3_sj, data = data_cl_sj, main = "Kmeans",geom = "point"),
fviz_cluster(res.HCPC, geom = "point", main = "Factor map"))
```


### 2.1.2 Avec hclust

```{r}
cah.wardD2_sj = hclust(dist(data_cl_sj),method="ward.D2")
plot(cah.wardD2_sj, main = "CAH sujets - critère de WARD2")
rect.hclust(cah.wardD2_sj,k=3)
```

```{r}
groupes.cah_sj = cutree(cah.wardD2_sj, 3)
table(groupes.cah_sj)
data_f$hclust_sj = groupes.cah_sj
data_f$hclust_sj = as.factor(data_f$hclust_sj)
```




```{r}
summary(coxph(Surv(time_to_deces, deces) ~  hclust_sj , data = data_f))
```





## 2.3 Algo EM


```{r}
mclust_sj = Mclust(data_cl_sj[,list_var])
```
```{r}
summary(mclust_sj)
mclust_sj
table(mclust_sj$classification)
```
```{r}
data_f$mclust_sj = mclust_sj$classification
```

```{r}
CG_mclust_sj = compareGroups( mclust_sj ~ .- nepp3 - km3_sj, data = data_f)
#pv = getResults(CG_km3_sj , "p.overall")

export_table_mclust = createTable(CG_mclust_sj)
export_table_mclust
```
```{r}
mclust3_sj = Mclust(data_cl_sj, G = 3)
```
```{r}
summary(mclust3_sj)
table(mclust3_sj$classification)
```
```{r}
data_f$mclust_sj = mclust_sj$classification
```

```{r}
CG_mclust_sj = compareGroups( mclust_sj ~ .- nepp3 - km3_sj, data = data_f)
#pv = getResults(CG_km3_sj , "p.overall")

export_table_mclust = createTable(CG_mclust_sj)
export_table_mclust
```
