---
title: "R Notebook"
output: html_notebook
---

(test_univar et cox_multivar_all contiennent les même variables)
```{r}
test_univar_names = c()
for(var in test_univar){
  test_univar_names = c(test_univar_names,names_echotracking[which(var == echotracking)])
}
```



# 1 Time on study as time scale

## 1.1 Données brutes
```{r}
m1_deces_tos$Name = as.character(m1_deces_tos$Name)
m1_deces_tos[m1_deces_tos$Name == "plaques1","Name"] = "plaques"
m2_deces_tos$Name = as.character(m2_deces_tos$Name)
m2_deces_tos$Name[m2_deces_tos$Name == "plaques1"] = "plaques"
m3_deces_tos$Name = as.character(m3_deces_tos$Name)
m3_deces_tos$Name[m3_deces_tos$Name == "plaques1"] = "plaques"
m4_deces_tos$Name = as.character(m4_deces_tos$Name)
m4_deces_tos$Name[m4_deces_tos$Name == "plaques1"] = "plaques"
m5_deces_tos$Name = as.character(m5_deces_tos$Name)
m5_deces_tos$Name[m5_deces_tos$Name == "plaques1"] = "plaques"
```
```{r}
m1_chd_tos$Name = as.character(m1_chd_tos$Name)
m1_chd_tos[m1_chd_tos$Name == "plaques1","Name"] = "plaques"
m2_chd_tos$Name = as.character(m2_chd_tos$Name)
m2_chd_tos$Name[m2_chd_tos$Name == "plaques1"] = "plaques"
m3_chd_tos$Name = as.character(m3_chd_tos$Name)
m3_chd_tos$Name[m3_chd_tos$Name == "plaques1"] = "plaques"
m4_chd_tos$Name = as.character(m4_chd_tos$Name)
m4_chd_tos$Name[m4_chd_tos$Name == "plaques1"] = "plaques"
m5_chd_tos$Name = as.character(m5_chd_tos$Name)
m5_chd_tos$Name[m5_chd_tos$Name == "plaques1"] = "plaques"
```
```{r}
res_cox_all_tab_tos = c()
model_names = c(" ", "Univariate", "Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
for(var in test_univar){
  
  param = c(var,rep(" ",6))
  
  HR_deces = c(" ", 
              round(list_univar_et_deces$HR[list_univar_et_deces$Name == var],2),
              round(m1_deces_tos$HR[m1_deces_tos$Name == var],2),
              round(m2_deces_tos$HR[m2_deces_tos$Name == var],2),
              round(m3_deces_tos$HR[m3_deces_tos$Name == var],2),
              round(m4_deces_tos$HR[m4_deces_tos$Name == var],2),
              round(m5_deces_tos$HR[m5_deces_tos$Name == var],2)
               )
  
  IC_deces = c(" ", 
              paste("[",round(list_univar_et_deces$ICinf[list_univar_et_deces$Name == var],2),
                    ";",round(list_univar_et_deces$ICsup[list_univar_et_deces$Name == var],2),"]"),
              
              paste("[",round(m1_deces_tos$ICinf[m1_deces_tos$Name == var],2),
                    ";",round(m1_deces_tos$ICsup[m1_deces_tos$Name == var],2),"]"),
              
              paste("[",round(m2_deces_tos$ICinf[m2_deces_tos$Name == var],2),
                    ";",round(m2_deces_tos$ICsup[m2_deces_tos$Name == var],2),"]"),
              
              paste("[",round(m3_deces_tos$ICinf[m3_deces_tos$Name == var],2),
                    ";",round(m3_deces_tos$ICsup[m3_deces_tos$Name == var],2),"]"),
              
              paste("[",round(m4_deces_tos$ICinf[m4_deces_tos$Name == var],2),
                    ";",round(m4_deces_tos$ICsup[m4_deces_tos$Name == var],2),"]"),
              paste("[",round(m5_deces_tos$ICinf[m5_deces_tos$Name == var],2),
                    ";",round(m5_deces_tos$ICsup[m5_deces_tos$Name == var],2),"]")
               )
  
  p_deces = c(" ", 
              paste(signif(list_univar_et_deces$p.value[list_univar_et_deces$Name == var],2),ifelse(list_univar_et_deces$p.value[list_univar_et_deces$Name == var] <= 0.05, "*"," ")),
              paste(signif(m1_deces_tos$p.value[m1_deces_tos$Name == var],2),ifelse(m1_deces_tos$p.value[m1_deces_tos$Name == var]<= 0.05, "*"," ")),
              paste(signif(m2_deces_tos$p.value[m2_deces_tos$Name == var],2),ifelse(m2_deces_tos$p.value[m2_deces_tos$Name == var]<=0.05,"*"," ")),
              paste(signif(m3_deces_tos$p.value[m3_deces_tos$Name == var],2),ifelse(m3_deces_tos$p.value[m3_deces_tos$Name == var]<=0.05,"*"," ")),
              paste(signif(m4_deces_tos$p.value[m4_deces_tos$Name == var],2),ifelse(m4_deces_tos$p.value[m4_deces_tos$Name == var]<=0.05,"*","")),
              paste(signif(m5_deces_tos$p.value[m5_deces_tos$Name == var],2),ifelse(m5_deces_tos$p.value[m5_deces_tos$Name == var]<=0.05,"*",""))
               )
  
  HR_chd = c(" ", 
              round(list_univar_et_chd$HR[list_univar_et_chd$Name == var],2),
              round(m1_chd_tos$HR[m1_chd_tos$Name == var],2),
              round(m2_chd_tos$HR[m2_chd_tos$Name == var],2),
              round(m3_chd_tos$HR[m3_chd_tos$Name == var],2),
              round(m4_chd_tos$HR[m4_chd_tos$Name == var],2),
              round(m5_chd_tos$HR[m5_chd_tos$Name == var],2)
               )
  
  IC_chd = c(" ", 
              paste("[",round(list_univar_et_chd$ICinf[list_univar_et_chd$Name == var],2),
                    ";",round(list_univar_et_chd$ICsup[list_univar_et_chd$Name == var],2),"]"),
              
              paste("[",round(m1_chd_tos$ICinf[m1_chd_tos$Name == var],2),
                    ";",round(m1_chd_tos$ICsup[m1_chd_tos$Name == var],2),"]"),
              
              paste("[",round(m2_chd_tos$ICinf[m2_chd_tos$Name == var],2),
                    ";",round(m2_chd_tos$ICsup[m2_chd_tos$Name == var],2),"]"),
              
              paste("[",round(m3_chd_tos$ICinf[m3_chd_tos$Name == var],2),
                    ";",round(m3_chd_tos$ICsup[m3_chd_tos$Name == var],2),"]"),
              
              paste("[",round(m4_chd_tos$ICinf[m4_chd_tos$Name == var],2),
                    ";",round(m4_chd_tos$ICsup[m4_chd_tos$Name == var],2),"]"),
             paste("[",round(m5_chd_tos$ICinf[m5_chd_tos$Name == var],2),
                    ";",round(m5_chd_tos$ICsup[m5_chd_tos$Name == var],2),"]")
               )
  
  p_chd = c(" ", 
              signif(list_univar_et_chd$p.value[list_univar_et_chd$Name == var],2),
              signif(m1_chd_tos$p.value[m1_chd_tos$Name == var],2),
              signif(m2_chd_tos$p.value[m2_chd_tos$Name == var],2),
              signif(m3_chd_tos$p.value[m3_chd_tos$Name == var],2),
              signif(m4_chd_tos$p.value[m4_chd_tos$Name == var],2),
              signif(m5_chd_tos$p.value[m5_chd_tos$Name == var],2)
               )
  
  tab = cbind(param,model_names,HR_deces,IC_deces,p_deces,HR_chd,IC_chd,p_chd)
  res_cox_all_tab_tos = rbind(res_cox_all_tab_tos,tab)
}

```
```{r}
colnames(res_cox_all_tab_tos)
```

```{r}
kable(res_cox_all_tab_tos, longtable = T, col.names = c(" " ," ", "HR" ,"IC","p", "HR" ,"IC","p"), align = "llcccccc", caption = "Time on study as time scale, données brutes") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 2, "Death" = 3, "CHD" = 3))
```
## 1.2 Données scaled
```{r}
m1_deces_tos_std$Name = as.character(m1_deces_tos_std$Name)
m1_deces_tos_std[m1_deces_tos_std$Name == "plaques1","Name"] = "plaques"
m2_deces_tos_std$Name = as.character(m2_deces_tos_std$Name)
m2_deces_tos_std$Name[m2_deces_tos_std$Name == "plaques1"] = "plaques"
m3_deces_tos_std$Name = as.character(m3_deces_tos_std$Name)
m3_deces_tos_std$Name[m3_deces_tos_std$Name == "plaques1"] = "plaques"
m4_deces_tos_std$Name = as.character(m4_deces_tos_std$Name)
m4_deces_tos_std$Name[m4_deces_tos_std$Name == "plaques1"] = "plaques"
m5_deces_tos_std$Name = as.character(m5_deces_tos_std$Name)
m5_deces_tos_std$Name[m5_deces_tos_std$Name == "plaques1"] = "plaques"
```
```{r}
m1_chd_tos_std$Name = as.character(m1_chd_tos_std$Name)
m1_chd_tos_std[m1_chd_tos_std$Name == "plaques1","Name"] = "plaques"
m2_chd_tos_std$Name = as.character(m2_chd_tos_std$Name)
m2_chd_tos_std$Name[m2_chd_tos_std$Name == "plaques1"] = "plaques"
m3_chd_tos_std$Name = as.character(m3_chd_tos_std$Name)
m3_chd_tos_std$Name[m3_chd_tos_std$Name == "plaques1"] = "plaques"
m4_chd_tos_std$Name = as.character(m4_chd_tos_std$Name)
m4_chd_tos_std$Name[m4_chd_tos_std$Name == "plaques1"] = "plaques"
m5_chd_tos_std$Name = as.character(m5_chd_tos_std$Name)
m5_chd_tos_std$Name[m5_chd_tos_std$Name == "plaques1"] = "plaques"
```
```{r}
res_cox_all_tab_tos_std = c()
model_names = c(" ", "Univariate", "Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
for(var in test_univar){
  
  param = c(var,rep(" ",6))
  
  HR_deces = c(" ", 
              round(list_univar_et_deces_std$HR[list_univar_et_deces_std$Name == var],2),
              round(m1_deces_tos_std$HR[m1_deces_tos_std$Name == var],2),
              round(m2_deces_tos_std$HR[m2_deces_tos_std$Name == var],2),
              round(m3_deces_tos_std$HR[m3_deces_tos_std$Name == var],2),
              round(m4_deces_tos_std$HR[m4_deces_tos_std$Name == var],2),
              round(m5_deces_tos_std$HR[m5_deces_tos_std$Name == var],2)
               )
  
  IC_deces = c(" ", 
              paste("[",round(list_univar_et_deces_std$ICinf[list_univar_et_deces_std$Name == var],2),
                    ";",round(list_univar_et_deces_std$ICsup[list_univar_et_deces_std$Name == var],2),"]"),
              
              paste("[",round(m1_deces_tos_std$ICinf[m1_deces_tos_std$Name == var],2),
                    ";",round(m1_deces_tos_std$ICsup[m1_deces_tos_std$Name == var],2),"]"),
              
              paste("[",round(m2_deces_tos_std$ICinf[m2_deces_tos_std$Name == var],2),
                    ";",round(m2_deces_tos_std$ICsup[m2_deces_tos_std$Name == var],2),"]"),
              
              paste("[",round(m3_deces_tos_std$ICinf[m3_deces_tos_std$Name == var],2),
                    ";",round(m3_deces_tos_std$ICsup[m3_deces_tos_std$Name == var],2),"]"),
              
              paste("[",round(m4_deces_tos_std$ICinf[m4_deces_tos_std$Name == var],2),
                    ";",round(m4_deces_tos_std$ICsup[m4_deces_tos_std$Name == var],2),"]"),
              paste("[",round(m5_deces_tos_std$ICinf[m5_deces_tos_std$Name == var],2),
                    ";",round(m5_deces_tos_std$ICsup[m5_deces_tos_std$Name == var],2),"]")
               )
  
  p_deces = c(" ", 
              paste(signif(list_univar_et_deces_std$p.value[list_univar_et_deces_std$Name == var],2),ifelse(list_univar_et_deces_std$p.value[list_univar_et_deces_std$Name == var] <= 0.05, "*"," ")),
              paste(signif(m1_deces_tos_std$p.value[m1_deces_tos_std$Name == var],2),ifelse(m1_deces_tos_std$p.value[m1_deces_tos_std$Name == var]<= 0.05, "*"," ")),
              paste(signif(m2_deces_tos_std$p.value[m2_deces_tos_std$Name == var],2),ifelse(m2_deces_tos_std$p.value[m2_deces_tos_std$Name == var]<=0.05,"*"," ")),
              paste(signif(m3_deces_tos_std$p.value[m3_deces_tos_std$Name == var],2),ifelse(m3_deces_tos_std$p.value[m3_deces_tos_std$Name == var]<=0.05,"*"," ")),
              paste(signif(m4_deces_tos_std$p.value[m4_deces_tos_std$Name == var],2),ifelse(m4_deces_tos_std$p.value[m4_deces_tos_std$Name == var]<=0.05,"*","")),
              paste(signif(m5_deces_tos_std$p.value[m5_deces_tos_std$Name == var],2),ifelse(m5_deces_tos_std$p.value[m5_deces_tos_std$Name == var]<=0.05,"*",""))
               )
  
  HR_chd = c(" ", 
              round(list_univar_et_chd_std$HR[list_univar_et_chd_std$Name == var],2),
              round(m1_chd_tos_std$HR[m1_chd_tos_std$Name == var],2),
              round(m2_chd_tos_std$HR[m2_chd_tos_std$Name == var],2),
              round(m3_chd_tos_std$HR[m3_chd_tos_std$Name == var],2),
              round(m4_chd_tos_std$HR[m4_chd_tos_std$Name == var],2),
              round(m5_chd_tos_std$HR[m5_chd_tos_std$Name == var],2)
               )
  
  IC_chd = c(" ", 
              paste("[",round(list_univar_et_chd_std$ICinf[list_univar_et_chd_std$Name == var],2),
                    ";",round(list_univar_et_chd_std$ICsup[list_univar_et_chd_std$Name == var],2),"]"),
              
              paste("[",round(m1_chd_tos_std$ICinf[m1_chd_tos_std$Name == var],2),
                    ";",round(m1_chd_tos_std$ICsup[m1_chd_tos_std$Name == var],2),"]"),
              
              paste("[",round(m2_chd_tos_std$ICinf[m2_chd_tos_std$Name == var],2),
                    ";",round(m2_chd_tos_std$ICsup[m2_chd_tos_std$Name == var],2),"]"),
              
              paste("[",round(m3_chd_tos_std$ICinf[m3_chd_tos_std$Name == var],2),
                    ";",round(m3_chd_tos_std$ICsup[m3_chd_tos_std$Name == var],2),"]"),
              
              paste("[",round(m4_chd_tos_std$ICinf[m4_chd_tos_std$Name == var],2),
                    ";",round(m4_chd_tos_std$ICsup[m4_chd_tos_std$Name == var],2),"]"),
             paste("[",round(m5_chd_tos_std$ICinf[m5_chd_tos_std$Name == var],2),
                    ";",round(m5_chd_tos_std$ICsup[m5_chd_tos_std$Name == var],2),"]")
               )
  
  p_chd = c(" ", 
              signif(list_univar_et_chd_std$p.value[list_univar_et_chd_std$Name == var],2),
              signif(m1_chd_tos_std$p.value[m1_chd_tos_std$Name == var],2),
              signif(m2_chd_tos_std$p.value[m2_chd_tos_std$Name == var],2),
              signif(m3_chd_tos_std$p.value[m3_chd_tos_std$Name == var],2),
              signif(m4_chd_tos_std$p.value[m4_chd_tos_std$Name == var],2),
              signif(m5_chd_tos_std$p.value[m5_chd_tos_std$Name == var],2)
               )
  
  tab = cbind(param,model_names,HR_deces,IC_deces,p_deces,HR_chd,IC_chd,p_chd)
  res_cox_all_tab_tos_std = rbind(res_cox_all_tab_tos_std,tab)
}

```

```{r}
kable(res_cox_all_tab_tos_std, longtable = T, col.names = c(" " ," ", "HR" ,"IC","p", "HR" ,"IC","p"), align = "llcccccc", caption = "Time on study as time scale, données scaled") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 2, "Death" = 3, "CHD" = 3))
```

# 2 Age as time scale

## 2.1 Données brutes

```{r}
m1_deces_as$Name = as.character(m1_deces_as$Name)
m1_deces_as[m1_deces_as$Name == "plaques1","Name"] = "plaques"
m2_deces_as$Name = as.character(m2_deces_as$Name)
m2_deces_as$Name[m2_deces_as$Name == "plaques1"] = "plaques"
m3_deces_as$Name = as.character(m3_deces_as$Name)
m3_deces_as$Name[m3_deces_as$Name == "plaques1"] = "plaques"
m4_deces_as$Name = as.character(m4_deces_as$Name)
m4_deces_as$Name[m4_deces_as$Name == "plaques1"] = "plaques"
m5_deces_as$Name = as.character(m5_deces_as$Name)
m5_deces_as$Name[m5_deces_as$Name == "plaques1"] = "plaques"
```
```{r}
m1_chd_as$Name = as.character(m1_chd_as$Name)
m1_chd_as[m1_chd_as$Name == "plaques1","Name"] = "plaques"
m2_chd_as$Name = as.character(m2_chd_as$Name)
m2_chd_as$Name[m2_chd_as$Name == "plaques1"] = "plaques"
m3_chd_as$Name = as.character(m3_chd_as$Name)
m3_chd_as$Name[m3_chd_as$Name == "plaques1"] = "plaques"
m4_chd_as$Name = as.character(m4_chd_as$Name)
m4_chd_as$Name[m4_chd_as$Name == "plaques1"] = "plaques"
m5_chd_as$Name = as.character(m5_chd_as$Name)
m5_chd_as$Name[m5_chd_as$Name == "plaques1"] = "plaques"
```
```{r}
res_cox_all_tab_as = c()
model_names = c(" ", "Univariate", "Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
for(var in test_univar){
  
  param = c(var,rep(" ",6))
  
  HR_deces = c(" ", 
              round(list_univar_et_deces$HR[list_univar_et_deces$Name == var],2),
              round(m1_deces_as$HR[m1_deces_as$Name == var],2),
              round(m2_deces_as$HR[m2_deces_as$Name == var],2),
              round(m3_deces_as$HR[m3_deces_as$Name == var],2),
              round(m4_deces_as$HR[m4_deces_as$Name == var],2),
              round(m5_deces_as$HR[m5_deces_as$Name == var],2)
               )
  
  IC_deces = c(" ", 
              paste("[",round(list_univar_et_deces$ICinf[list_univar_et_deces$Name == var],2),
                    ";",round(list_univar_et_deces$ICsup[list_univar_et_deces$Name == var],2),"]"),
              
              paste("[",round(m1_deces_as$ICinf[m1_deces_as$Name == var],2),
                    ";",round(m1_deces_as$ICsup[m1_deces_as$Name == var],2),"]"),
              
              paste("[",round(m2_deces_as$ICinf[m2_deces_as$Name == var],2),
                    ";",round(m2_deces_as$ICsup[m2_deces_as$Name == var],2),"]"),
              
              paste("[",round(m3_deces_as$ICinf[m3_deces_as$Name == var],2),
                    ";",round(m3_deces_as$ICsup[m3_deces_as$Name == var],2),"]"),
              
              paste("[",round(m4_deces_as$ICinf[m4_deces_as$Name == var],2),
                    ";",round(m4_deces_as$ICsup[m4_deces_as$Name == var],2),"]"),
              paste("[",round(m5_deces_as$ICinf[m5_deces_as$Name == var],2),
                    ";",round(m5_deces_as$ICsup[m5_deces_as$Name == var],2),"]")
               )
  
  p_deces = c(" ", 
              paste(signif(list_univar_et_deces$p.value[list_univar_et_deces$Name == var],2),ifelse(list_univar_et_deces$p.value[list_univar_et_deces$Name == var] <= 0.05, "*"," ")),
              paste(signif(m1_deces_as$p.value[m1_deces_as$Name == var],2),ifelse(m1_deces_as$p.value[m1_deces_as$Name == var]<= 0.05, "*"," ")),
              paste(signif(m2_deces_as$p.value[m2_deces_as$Name == var],2),ifelse(m2_deces_as$p.value[m2_deces_as$Name == var]<=0.05,"*"," ")),
              paste(signif(m3_deces_as$p.value[m3_deces_as$Name == var],2),ifelse(m3_deces_as$p.value[m3_deces_as$Name == var]<=0.05,"*"," ")),
              paste(signif(m4_deces_as$p.value[m4_deces_as$Name == var],2),ifelse(m4_deces_as$p.value[m4_deces_as$Name == var]<=0.05,"*","")),
              paste(signif(m5_deces_as$p.value[m5_deces_as$Name == var],2),ifelse(m5_deces_as$p.value[m5_deces_as$Name == var]<=0.05,"*",""))
               )
  
  HR_chd = c(" ", 
              round(list_univar_et_chd$HR[list_univar_et_chd$Name == var],2),
              round(m1_chd_as$HR[m1_chd_as$Name == var],2),
              round(m2_chd_as$HR[m2_chd_as$Name == var],2),
              round(m3_chd_as$HR[m3_chd_as$Name == var],2),
              round(m4_chd_as$HR[m4_chd_as$Name == var],2),
              round(m5_chd_as$HR[m5_chd_as$Name == var],2)
               )
  
  IC_chd = c(" ", 
              paste("[",round(list_univar_et_chd$ICinf[list_univar_et_chd$Name == var],2),
                    ";",round(list_univar_et_chd$ICsup[list_univar_et_chd$Name == var],2),"]"),
              
              paste("[",round(m1_chd_as$ICinf[m1_chd_as$Name == var],2),
                    ";",round(m1_chd_as$ICsup[m1_chd_as$Name == var],2),"]"),
              
              paste("[",round(m2_chd_as$ICinf[m2_chd_as$Name == var],2),
                    ";",round(m2_chd_as$ICsup[m2_chd_as$Name == var],2),"]"),
              
              paste("[",round(m3_chd_as$ICinf[m3_chd_as$Name == var],2),
                    ";",round(m3_chd_as$ICsup[m3_chd_as$Name == var],2),"]"),
              
              paste("[",round(m4_chd_as$ICinf[m4_chd_as$Name == var],2),
                    ";",round(m4_chd_as$ICsup[m4_chd_as$Name == var],2),"]"),
             paste("[",round(m5_chd_as$ICinf[m5_chd_as$Name == var],2),
                    ";",round(m5_chd_as$ICsup[m5_chd_as$Name == var],2),"]")
               )
  
  p_chd = c(" ", 
              signif(list_univar_et_chd$p.value[list_univar_et_chd$Name == var],2),
              signif(m1_chd_as$p.value[m1_chd_as$Name == var],2),
              signif(m2_chd_as$p.value[m2_chd_as$Name == var],2),
              signif(m3_chd_as$p.value[m3_chd_as$Name == var],2),
              signif(m4_chd_as$p.value[m4_chd_as$Name == var],2),
              signif(m5_chd_as$p.value[m5_chd_as$Name == var],2)
               )
  
  tab = cbind(param,model_names,HR_deces,IC_deces,p_deces,HR_chd,IC_chd,p_chd)
  res_cox_all_tab_as = rbind(res_cox_all_tab_as,tab)
}

```


```{r}
kable(res_cox_all_tab_as, longtable = T, col.names = c(" " ," ", "HR" ,"IC","p", "HR" ,"IC","p"), align = "llcccccc", caption = "Age as time scale") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 2, "Death" = 3, "CHD" = 3))
```
## 2.2 Données scaled

```{r}
m1_deces_as_std$Name = as.character(m1_deces_as_std$Name)
m1_deces_as_std[m1_deces_as_std$Name == "plaques1","Name"] = "plaques"
m2_deces_as_std$Name = as.character(m2_deces_as_std$Name)
m2_deces_as_std$Name[m2_deces_as_std$Name == "plaques1"] = "plaques"
m3_deces_as_std$Name = as.character(m3_deces_as_std$Name)
m3_deces_as_std$Name[m3_deces_as_std$Name == "plaques1"] = "plaques"
m4_deces_as_std$Name = as.character(m4_deces_as_std$Name)
m4_deces_as_std$Name[m4_deces_as_std$Name == "plaques1"] = "plaques"
m5_deces_as_std$Name = as.character(m5_deces_as_std$Name)
m5_deces_as_std$Name[m5_deces_as_std$Name == "plaques1"] = "plaques"
```
```{r}
m1_chd_as_std$Name = as.character(m1_chd_as_std$Name)
m1_chd_as_std[m1_chd_as_std$Name == "plaques1","Name"] = "plaques"
m2_chd_as_std$Name = as.character(m2_chd_as_std$Name)
m2_chd_as_std$Name[m2_chd_as_std$Name == "plaques1"] = "plaques"
m3_chd_as_std$Name = as.character(m3_chd_as_std$Name)
m3_chd_as_std$Name[m3_chd_as_std$Name == "plaques1"] = "plaques"
m4_chd_as_std$Name = as.character(m4_chd_as_std$Name)
m4_chd_as_std$Name[m4_chd_as_std$Name == "plaques1"] = "plaques"
m5_chd_as_std$Name = as.character(m5_chd_as_std$Name)
m5_chd_as_std$Name[m5_chd_as_std$Name == "plaques1"] = "plaques"
```


```{r}
res_cox_all_tab_as_std = c()
model_names = c(" ", "Univariate", "Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
for(var in test_univar){
  
  param = c(var,rep(" ",6))
  
  HR_deces = c(" ", 
              round(list_univar_et_deces_std$HR[list_univar_et_deces_std$Name == var],2),
              round(m1_deces_as_std$HR[m1_deces_as_std$Name == var],2),
              round(m2_deces_as_std$HR[m2_deces_as_std$Name == var],2),
              round(m3_deces_as_std$HR[m3_deces_as_std$Name == var],2),
              round(m4_deces_as_std$HR[m4_deces_as_std$Name == var],2),
              round(m5_deces_as_std$HR[m5_deces_as_std$Name == var],2)
               )
  
  IC_deces = c(" ", 
              paste("[",round(list_univar_et_deces_std$ICinf[list_univar_et_deces_std$Name == var],2),
                    ";",round(list_univar_et_deces_std$ICsup[list_univar_et_deces_std$Name == var],2),"]"),
              
              paste("[",round(m1_deces_as_std$ICinf[m1_deces_as_std$Name == var],2),
                    ";",round(m1_deces_as_std$ICsup[m1_deces_as_std$Name == var],2),"]"),
              
              paste("[",round(m2_deces_as_std$ICinf[m2_deces_as_std$Name == var],2),
                    ";",round(m2_deces_as_std$ICsup[m2_deces_as_std$Name == var],2),"]"),
              
              paste("[",round(m3_deces_as_std$ICinf[m3_deces_as_std$Name == var],2),
                    ";",round(m3_deces_as_std$ICsup[m3_deces_as_std$Name == var],2),"]"),
              
              paste("[",round(m4_deces_as_std$ICinf[m4_deces_as_std$Name == var],2),
                    ";",round(m4_deces_as_std$ICsup[m4_deces_as_std$Name == var],2),"]"),
              paste("[",round(m5_deces_as_std$ICinf[m5_deces_as_std$Name == var],2),
                    ";",round(m5_deces_as_std$ICsup[m5_deces_as_std$Name == var],2),"]")
               )
  
  p_deces = c(" ", 
              paste(signif(list_univar_et_deces_std$p.value[list_univar_et_deces_std$Name == var],2),ifelse(list_univar_et_deces_std$p.value[list_univar_et_deces_std$Name == var] <= 0.05, "*"," ")),
              paste(signif(m1_deces_as_std$p.value[m1_deces_as_std$Name == var],2),ifelse(m1_deces_as_std$p.value[m1_deces_as_std$Name == var]<= 0.05, "*"," ")),
              paste(signif(m2_deces_as_std$p.value[m2_deces_as_std$Name == var],2),ifelse(m2_deces_as_std$p.value[m2_deces_as_std$Name == var]<=0.05,"*"," ")),
              paste(signif(m3_deces_as_std$p.value[m3_deces_as_std$Name == var],2),ifelse(m3_deces_as_std$p.value[m3_deces_as_std$Name == var]<=0.05,"*"," ")),
              paste(signif(m4_deces_as_std$p.value[m4_deces_as_std$Name == var],2),ifelse(m4_deces_as_std$p.value[m4_deces_as_std$Name == var]<=0.05,"*","")),
              paste(signif(m5_deces_as_std$p.value[m5_deces_as_std$Name == var],2),ifelse(m5_deces_as_std$p.value[m5_deces_as_std$Name == var]<=0.05,"*",""))
               )
  
  HR_chd = c(" ", 
              round(list_univar_et_chd_std$HR[list_univar_et_chd_std$Name == var],2),
              round(m1_chd_as_std$HR[m1_chd_as_std$Name == var],2),
              round(m2_chd_as_std$HR[m2_chd_as_std$Name == var],2),
              round(m3_chd_as_std$HR[m3_chd_as_std$Name == var],2),
              round(m4_chd_as_std$HR[m4_chd_as_std$Name == var],2),
              round(m5_chd_as_std$HR[m5_chd_as_std$Name == var],2)
               )
  
  IC_chd = c(" ", 
              paste("[",round(list_univar_et_chd_std$ICinf[list_univar_et_chd_std$Name == var],2),
                    ";",round(list_univar_et_chd_std$ICsup[list_univar_et_chd_std$Name == var],2),"]"),
              
              paste("[",round(m1_chd_as_std$ICinf[m1_chd_as_std$Name == var],2),
                    ";",round(m1_chd_as_std$ICsup[m1_chd_as_std$Name == var],2),"]"),
              
              paste("[",round(m2_chd_as_std$ICinf[m2_chd_as_std$Name == var],2),
                    ";",round(m2_chd_as_std$ICsup[m2_chd_as_std$Name == var],2),"]"),
              
              paste("[",round(m3_chd_as_std$ICinf[m3_chd_as_std$Name == var],2),
                    ";",round(m3_chd_as_std$ICsup[m3_chd_as_std$Name == var],2),"]"),
              
              paste("[",round(m4_chd_as_std$ICinf[m4_chd_as_std$Name == var],2),
                    ";",round(m4_chd_as_std$ICsup[m4_chd_as_std$Name == var],2),"]"),
             paste("[",round(m5_chd_as_std$ICinf[m5_chd_as_std$Name == var],2),
                    ";",round(m5_chd_as_std$ICsup[m5_chd_as_std$Name == var],2),"]")
               )
  
  p_chd = c(" ", 
              signif(list_univar_et_chd_std$p.value[list_univar_et_chd_std$Name == var],2),
              signif(m1_chd_as_std$p.value[m1_chd_as_std$Name == var],2),
              signif(m2_chd_as_std$p.value[m2_chd_as_std$Name == var],2),
              signif(m3_chd_as_std$p.value[m3_chd_as_std$Name == var],2),
              signif(m4_chd_as_std$p.value[m4_chd_as_std$Name == var],2),
              signif(m5_chd_as_std$p.value[m5_chd_as_std$Name == var],2)
               )
  
  tab = cbind(param,model_names,HR_deces,IC_deces,p_deces,HR_chd,IC_chd,p_chd)
  res_cox_all_tab_as_std = rbind(res_cox_all_tab_as_std,tab)
}

```


```{r}
kable(res_cox_all_tab_as_std, longtable = T, col.names = c(" " ," ", "HR" ,"IC","p", "HR" ,"IC","p"), align = "llcccccc", caption = "Age as time scale, données scaled") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 2, "Death" = 3, "CHD" = 3))
```






