---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# 1 Deces


```{r}
f1_deces_tos = formula(Surv(time_to_deces,event = deces) ~ age0 + sexe ,env = data4)

f2_deces_tos = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4)

f3_deces_tos = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4)

f4_deces_tos = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4)
```
```{r}
c_harell_m4base_deces_tos = concordance(coxph(f4_deces_tos, data = data4))$concordance
c_harell_m4base_deces_tos
```

```{r}
f1_deces_tos_std = formula(Surv(time_to_deces,event = deces) ~ age0 + sexe ,env = data4_std)

f2_deces_tos_std = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4_std)

f3_deces_tos_std = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4_std)

f4_deces_tos_std = formula(Surv(time_to_deces,deces) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4_std)
```

```{r}
m1_deces_tos = cox_multivar2(f1_deces_tos,cox_univar_deces_tos,data4, round = F)
m2_deces_tos = cox_multivar2(f2_deces_tos,cox_univar_deces_tos,data4, round = F)
m3_deces_tos = cox_multivar2(f3_deces_tos,cox_univar_deces_tos,data4, round = F)
m4_deces_tos = cox_multivar2(f4_deces_tos,cox_univar_deces_tos,data4, round = F)
```
```{r}
m1_deces_tos_std = cox_multivar2(f1_deces_tos_std,cox_univar_deces_tos,data4_std, round = F)
m2_deces_tos_std = cox_multivar2(f2_deces_tos_std,cox_univar_deces_tos,data4_std, round = F)
m3_deces_tos_std = cox_multivar2(f3_deces_tos_std,cox_univar_deces_tos,data4_std, round = F)
m4_deces_tos_std = cox_multivar2(f4_deces_tos_std,cox_univar_deces_tos,data4_std, round = F)
```
```{r}
m1_deces_tos$Name = as.character(m1_deces_tos$Name)
m1_deces_tos[m1_deces_tos$Name == "plaques1","Name"] = "plaques"
m2_deces_tos$Name = as.character(m2_deces_tos$Name)
m2_deces_tos$Name[m2_deces_tos$Name == "plaques1"] = "plaques"
m3_deces_tos$Name = as.character(m3_deces_tos$Name)
m3_deces_tos$Name[m3_deces_tos$Name == "plaques1"] = "plaques"
m4_deces_tos$Name = as.character(m4_deces_tos$Name)
m4_deces_tos$Name[m4_deces_tos$Name == "plaques1"] = "plaques"
```
```{r}
m1_deces_tos_std$Name = as.character(m1_deces_tos_std$Name)
m1_deces_tos_std[m1_deces_tos_std$Name == "plaques1","Name"] = "plaques"
m2_deces_tos_std$Name = as.character(m2_deces_tos_std$Name)
m2_deces_tos_std$Name[m2_deces_tos_std$Name == "plaques1"] = "plaques"
m3_deces_tos_std$Name = as.character(m3_deces_tos_std$Name)
m3_deces_tos_std$Name[m3_deces_tos_std$Name == "plaques1"] = "plaques"
m4_deces_tos_std$Name = as.character(m4_deces_tos_std$Name)
m4_deces_tos_std$Name[m4_deces_tos_std$Name == "plaques1"] = "plaques"
```
```{r}
cox_multivar_deces_tos = m4_deces_tos$Name[m4_deces_tos$pv_signif == 1]
```

# 2 CHD
```{r}
f1_chd_tos = formula(Surv(time_to_chd,event = chd) ~ age0 + sexe ,env = data4)

f2_chd_tos = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4)

f3_chd_tos = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4)

f4_chd_tos = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4)
```
```{r}
c_harell_m4base_chd_tos = concordance(coxph(f4_chd_tos, data = data4))$concordance
c_harell_m4base_chd_tos
```

```{r}
f1_chd_tos_std = formula(Surv(time_to_chd,event = chd) ~ age0 + sexe ,env = data4_std)

f2_chd_tos_std = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4_std)

f3_chd_tos_std = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4_std)

f4_chd_tos_std = formula(Surv(time_to_chd,chd) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4_std)
```

```{r}
m1_chd_tos = cox_multivar2(f1_chd_tos,cox_univar_chd_tos,data4, round = F)
m2_chd_tos = cox_multivar2(f2_chd_tos,cox_univar_chd_tos,data4, round = F)
m3_chd_tos = cox_multivar2(f3_chd_tos,cox_univar_chd_tos,data4, round = F)
m4_chd_tos = cox_multivar2(f4_chd_tos,cox_univar_chd_tos,data4, round = F)
```
```{r}
m1_chd_tos_std = cox_multivar2(f1_chd_tos_std,cox_univar_chd_tos,data4_std, round = F)
m2_chd_tos_std = cox_multivar2(f2_chd_tos_std,cox_univar_chd_tos,data4_std, round = F)
m3_chd_tos_std = cox_multivar2(f3_chd_tos_std,cox_univar_chd_tos,data4_std, round = F)
m4_chd_tos_std = cox_multivar2(f4_chd_tos_std,cox_univar_chd_tos,data4_std, round = F)
```
```{r}
m1_chd_tos$Name = as.character(m1_chd_tos$Name)
m1_chd_tos[m1_chd_tos$Name == "plaques1","Name"] = "plaques"
m2_chd_tos$Name = as.character(m2_chd_tos$Name)
m2_chd_tos$Name[m2_chd_tos$Name == "plaques1"] = "plaques"
m3_chd_tos$Name = as.character(m3_chd_tos$Name)
m3_chd_tos$Name[m3_chd_tos$Name == "plaques1"] = "plaques"
m4_chd_tos$Name = as.character(m4_chd_tos$Name)
m4_chd_tos$Name[m4_chd_tos$Name == "plaques1"] = "plaques"
```
```{r}
m1_chd_tos_std$Name = as.character(m1_chd_tos_std$Name)
m1_chd_tos_std[m1_chd_tos_std$Name == "plaques1","Name"] = "plaques"
m2_chd_tos_std$Name = as.character(m2_chd_tos_std$Name)
m2_chd_tos_std$Name[m2_chd_tos_std$Name == "plaques1"] = "plaques"
m3_chd_tos_std$Name = as.character(m3_chd_tos_std$Name)
m3_chd_tos_std$Name[m3_chd_tos_std$Name == "plaques1"] = "plaques"
m4_chd_tos_std$Name = as.character(m4_chd_tos_std$Name)
m4_chd_tos_std$Name[m4_chd_tos_std$Name == "plaques1"] = "plaques"
```
```{r}
cox_multivar_chd_tos = m4_chd_tos$Name[m4_chd_tos$pv_signif == 1]
```
# 3 Stroke
```{r}
data4$stroke = as.numeric(as.character(data4$stroke))
data4_std$stroke = as.numeric(as.character(data4_std$stroke))
```

```{r}
f1_stroke_tos = formula(Surv(time_to_stroke,event = stroke) ~ age0 + sexe ,env = data4)

f2_stroke_tos = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4)

f3_stroke_tos = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4)

f4_stroke_tos = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4)
```
```{r}
c_harell_m4base_stroke_tos = concordance(coxph(f4_stroke_tos, data = data4))$concordance
c_harell_m4base_stroke_tos
```

```{r}
f1_stroke_tos_std = formula(Surv(time_to_stroke,event = stroke) ~ age0 + sexe ,env = data4_std)

f2_stroke_tos_std = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi, env = data4_std)

f3_stroke_tos_std = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl, env = data4_std)

f4_stroke_tos_std = formula(Surv(time_to_stroke,stroke) ~ age0 + sexe + qm16 + qm10 + bmi + diab + bio10 + trb17 + ldl + mbp, env = data4_std)
```

```{r}
m1_stroke_tos = cox_multivar2(f1_stroke_tos,cox_univar_stroke_tos,data4, round = F)
m2_stroke_tos = cox_multivar2(f2_stroke_tos,cox_univar_stroke_tos,data4, round = F)
m3_stroke_tos = cox_multivar2(f3_stroke_tos,cox_univar_stroke_tos,data4, round = F)
m4_stroke_tos = cox_multivar2(f4_stroke_tos,cox_univar_stroke_tos,data4, round = F)
```
```{r}
m1_stroke_tos_std = cox_multivar2(f1_stroke_tos_std,cox_univar_stroke_tos,data4_std, round = F)
m2_stroke_tos_std = cox_multivar2(f2_stroke_tos_std,cox_univar_stroke_tos,data4_std, round = F)
m3_stroke_tos_std = cox_multivar2(f3_stroke_tos_std,cox_univar_stroke_tos,data4_std, round = F)
m4_stroke_tos_std = cox_multivar2(f4_stroke_tos_std,cox_univar_stroke_tos,data4_std, round = F)
```
```{r}
m1_stroke_tos$Name = as.character(m1_stroke_tos$Name)
m1_stroke_tos[m1_stroke_tos$Name == "plaques1","Name"] = "plaques"
m2_stroke_tos$Name = as.character(m2_stroke_tos$Name)
m2_stroke_tos$Name[m2_stroke_tos$Name == "plaques1"] = "plaques"
m3_stroke_tos$Name = as.character(m3_stroke_tos$Name)
m3_stroke_tos$Name[m3_stroke_tos$Name == "plaques1"] = "plaques"
m4_stroke_tos$Name = as.character(m4_stroke_tos$Name)
m4_stroke_tos$Name[m4_stroke_tos$Name == "plaques1"] = "plaques"
```
```{r}
m1_stroke_tos_std$Name = as.character(m1_stroke_tos_std$Name)
m1_stroke_tos_std[m1_stroke_tos_std$Name == "plaques1","Name"] = "plaques"
m2_stroke_tos_std$Name = as.character(m2_stroke_tos_std$Name)
m2_stroke_tos_std$Name[m2_stroke_tos_std$Name == "plaques1"] = "plaques"
m3_stroke_tos_std$Name = as.character(m3_stroke_tos_std$Name)
m3_stroke_tos_std$Name[m3_stroke_tos_std$Name == "plaques1"] = "plaques"
m4_stroke_tos_std$Name = as.character(m4_stroke_tos_std$Name)
m4_stroke_tos_std$Name[m4_stroke_tos_std$Name == "plaques1"] = "plaques"
```
```{r}
cox_multivar_stroke_tos = m4_stroke_tos$Name[m4_stroke_tos$pv_signif == 1]
```
