---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
# data4$time_to_deces = as.numeric(as.character(data4$time_to_deces))
# data4$time_to_chd = as.numeric(as.character(data4$time_to_chd))
# data4$time_to_stroke = as.numeric(as.character(data4$time_to_stroke))
# 
#data4$deces = as.numeric(as.character(data4$deces))
#data4$chd = as.numeric(as.character(data4$chd))
#data4$stroke = as.numeric(as.character(data4$stroke))
# 
# data4_std$time_to_deces = as.numeric(as.character(data4_std$time_to_deces))
# data4_std$time_to_chd = as.numeric(as.character(data4_std$time_to_chd))
# data4_std$time_to_stroke = as.numeric(as.character(data4_std$time_to_stroke))
# 
#data4_std$deces = as.numeric(as.character(data4_std$deces))
#data4_std$chd = as.numeric(as.character(data4_std$chd))
#data4_std$stroke = as.numeric(as.character(data4_std$stroke))
```

```{r}
# data4$age_at_deces = as.numeric(as.character(data4$age_at_deces))
# data4$age_at_chd = as.numeric(as.character(data4$age_at_chd))
# data4$age_at_stroke = as.numeric(as.character(data4$age_at_stroke))
# 
# data4_std$age_at_deces = as.numeric(as.character(data4_std$age_at_deces))
# data4_std$age_at_chd = as.numeric(as.character(data4_std$age_at_chd))
# data4_std$age_at_stroke = as.numeric(as.character(data4_std$age_at_stroke))
```

# 1. Modèls de Cox univariés pour toutes les variables d'échotracking (clean)

Ici avec l'argument round = F pour pouvoir tracer le graph


## 1.1 Time on study as time scale
```{r}
i = 1
list_univar_tos = list()
list_univar_tos_std = list()

for(evt in c("deces","chd", "stroke")){

  time = paste0("time_to_",evt)
  res_univar = data.frame()
  res_univar_std = data.frame()

  for(var in c(stiffness_anat,stiffness_dyna)){

    cox = cox_univar(time = time, evt = evt, param = var, data4, round = F)
    cox_std = cox_univar(time = time, evt = evt, param = var, data4_std, round = F)

    res_univar = rbind(res_univar, cox)
    res_univar_std = rbind(res_univar_std, cox_std)
  }

  res_univar$Evt = rep(evt,nrow(res_univar))
  res_univar_std$Evt = rep(evt,nrow(res_univar_std))

  list_univar_tos[[i]] = res_univar
  list_univar_tos_std[[i]] = res_univar_std

  i = i + 1
}
rm(i);
rm(res_univar); rm(res_univar_std);
rm(cox);rm(cox_std)

names(list_univar_tos) = c("deces","chd","stroke")
names(list_univar_tos_std) = c("deces","chd", "stroke")
```




## 1.2 Age as time scale 

```{r}
i = 1
list_univar_as = list()
list_univar_as_std = list()

for(evt in c("deces","chd", "stroke")){

  time = paste0("age_at_",evt)
  res_univar = data.frame()
  res_univar_std = data.frame()

  for(var in c(stiffness_anat,stiffness_dyna)){

    cox = cox_univar_as("age0",time, evt, var, data4, round = F)
    cox_std = cox_univar_as("age0",time,evt, var, data4_std, round = F)

    res_univar = rbind(res_univar, cox)
    res_univar_std = rbind(res_univar_std, cox_std)
  }

   res_univar$Evt = rep(evt,nrow(res_univar))
   res_univar_std$Evt = rep(evt,nrow(res_univar_std))
 
   list_univar_as[[i]] = res_univar
   list_univar_as_std[[i]] = res_univar_std
 
   i = i + 1
 }
 rm(i);
 rm(res_univar); rm(res_univar_std);
 rm(cox); rm(cox_std)
 
 names(list_univar_as) = c("deces","chd","stroke")
 names(list_univar_as_std) = c("deces","chd","stroke")
```





# 2. Stockage des param signif

On stock les param signif dans cox univarié 
```{r}
cox_univar_deces_tos = as.character(list_univar_tos[["deces"]]$Name[list_univar_tos[["deces"]]$pv_signif == 1 ])

cox_univar_chd_tos = as.character(list_univar_tos[["chd"]]$Name[list_univar_tos[["chd"]]$pv_signif == 1])

cox_univar_stroke_tos = as.character(list_univar_tos[["stroke"]]$Name[list_univar_tos[["stroke"]]$pv_signif == 1])
```
```{r}
cox_univar_deces_as = as.character(list_univar_as[["deces"]]$Name[list_univar_as[["deces"]]$pv_signif == 1 ])

cox_univar_chd_as = as.character(list_univar_as[["chd"]]$Name[list_univar_as[["chd"]]$pv_signif == 1])

cox_univar_stroke_as = as.character(list_univar_as[["stroke"]]$Name[list_univar_as[["stroke"]]$pv_signif == 1])
```
```{r}
length(cox_univar_deces_tos)
length(cox_univar_chd_tos)
length(cox_univar_stroke_tos)

length(cox_univar_deces_as)
length(cox_univar_chd_as)
length(cox_univar_stroke_as)
```









