---
title: "R Notebook"
output: html_notebook
---

# 1. Modèles de cox univariés avec une interaction avec le sexe

## 1.1 Avec le deces comme outcome
```{r}
i = 1
list_univar_et_interSexe = list()
evt = "deces"
time = paste0("time_to_",evt)
res_univar_et_interSexe = data.frame()
  
for(var in test_univar_deces){
    cox = cox_univar(time, var, evt, data2, round = F, interaction = T, var.inter = "sexe")
    res_univar_et_interSexe = rbind(res_univar_et_interSexe, cox)
    }
  
  res_univar_et_interSexe$Evt = rep(evt,nrow(res_univar_et_interSexe))
  
  list_univar_et_interSexe[[i]] = res_univar_et_interSexe
  
  i = i + 1

rm(i);
rm(res_univar_et_interSexe);
rm(cox)

names(list_univar_et_interSexe) = c("deces")
```

```{r}
list_univar_et_interSexe[["deces"]]
```
```{r}
plot_pv_HR(list_univar_et_interSexe[["deces"]])
```
## 1.2 Avec le CHD comme outcome
```{r}
i = 1
list_univar_et_interSexe = list()
evt = "chd"
time = paste0("time_to_",evt)
res_univar_et_interSexe = data.frame()
  
for(var in test_univar_chd){
    cox = cox_univar(time, var, evt, data2, round = F, interaction = T, var.inter = "sexe")
    res_univar_et_interSexe = rbind(res_univar_et_interSexe, cox)
    }
  
  res_univar_et_interSexe$Evt = rep(evt,nrow(res_univar_et_interSexe))
  
  list_univar_et_interSexe[[i]] = res_univar_et_interSexe
  
  i = i + 1

rm(i);
rm(res_univar_et_interSexe);
rm(cox)

names(list_univar_et_interSexe) = c("chd")
```

```{r}
list_univar_et_interSexe[["chd"]]
```
```{r}
plot_pv_HR(list_univar_et_interSexe[["chd"]])
```
#2. Visualisation

```{r}
for(var in echotracking_clean){
  if(is.numeric(data2[,var])){
    print(ggplot(data2, aes(x=data2[,var], fill=sexe)) +  geom_density(alpha=.5) + ggtitle(var))
  }
}
```

```{r}
t.test(data2$diam_bm ~ data2$sexe)
summary(coxph(Surv(time_to_deces,deces)~diam_bm*sexe, data = data2))
```

