---
title: "Gestion des valeurs manquantes"
output: html_notebook
---


# 1. Imputation

```{r}
colnames(data2[,c(var_ajust[-11],stiffness_anat,stiffness_dyna,"deces","chd","stroke","time_to_deces","time_to_chd","time_to_stroke")])
```

```{r}
mat_pred = matrix(rep(1,29*29), nrow = 29, ncol = 29)
mat_pred[,c(17,22,24:29)]  = 0
mat_pred[c(17,22,24:29),]  = 0
#mat_pred
mat_pred[17,]
meth=c("","","polyreg","polyreg","polyreg",
       "pmm","pmm","pmm","pmm","sample",
       "sample","sample","logreg","sample","pmm",
       "pmm","","sample","sample","sample",
       "sample","","sample","","",
       
       "","","","")
length(meth)
```
```{r}
data2$deces = as.numeric(as.character(data2$deces))
data2$chd = as.numeric(as.character(data2$chd))
data2$stroke = as.numeric(as.character(data2$stroke))
data2$time_to_deces = as.numeric(as.character(data2$time_to_deces))
data2$time_to_chd = as.numeric(as.character(data2$time_to_chd))
data2$time_to_stroke = as.numeric(as.character(data2$time_to_stroke))
```


```{r}
data_mice = mice(data2[,c(var_ajust[-11],stiffness_anat,stiffness_dyna,"deces","chd","stroke","time_to_deces","time_to_chd","time_to_stroke")], m = 5, maxit = 10, predictorMatrix = mat_pred, method = meth)
```
```{r}
data_mice$loggedEvents
data_mice$method
```
```{r}
plot(data_mice)
```

```{r}
for(i in 1:data_mice$m){
  data_mice$imp$stiffness[,i] = as.numeric(sqrt(1/(data_mice$imp$coeffDist[,i])*1000))
  data_mice$imp$pwvloc2[,i] =  as.numeric(1/sqrt(data_mice$imp$coeffDist[,i]*1.06))
}
```
```{r}
sum(is.na(complete(data_mice,1)))
```
```{r}
no_scale_imp = c("sexe","qm16","qm10","diab","plaques","deces","chd","stroke","time_to_deces","time_to_chd","time_to_stroke")
```


# 2. Modèles univariés

```{r}
HR_deces = c()
p_deces = c()
HR_chd = c()
p_chd= c()
HR_stroke = c()
p_stroke= c()
name = c()
for(param in c(stiffness_anat,stiffness_dyna)){
  list_deces = list()
  list_chd = list()
  list_stroke = list()
  name = c(name, as.character(df_echotracking$Tidy[df_echotracking$Missy == param]))
for(i in 1:data_mice$m){
  d = complete(data_mice,i)
for(j in colnames(d)){
   if(!(j %in% no_scale_imp)){
    d[,j]= (d[,j]-mean(d[,j]))/sd(d[,j])
   }
  }
  f_deces = as.formula(paste("Surv(time_to_deces,deces)~",param))
  f_chd = as.formula(paste("Surv(time_to_chd,chd)~",param))
  f_stroke = as.formula(paste("Surv(time_to_stroke,stroke)~",param))
  list_deces[[i]] = coxph(f_deces, data = d)
  list_chd[[i]] = coxph(f_chd, data = d)
  list_stroke[[i]] = coxph(f_stroke, data = d)
}

list_deces = as.mira(list_deces)
list_chd = as.mira(list_chd)
list_stroke = as.mira(list_stroke)

pool_deces = pool(list_deces)
pool_chd = pool(list_chd)
pool_stroke = pool(list_stroke)

sum_pool_deces = summary(pool_deces)
sum_pool_chd = summary(pool_chd)
sum_pool_stroke = summary(pool_stroke)

HR_deces = c(HR_deces, exp(sum_pool_deces$estimate))
HR_chd = c(HR_chd, exp(sum_pool_chd$estimate))
HR_stroke = c(HR_stroke, exp(sum_pool_stroke$estimate))
p_deces = c(p_deces, sum_pool_deces$p.value)
p_chd = c(p_chd, sum_pool_chd$p.value)
p_stroke = c(p_stroke, sum_pool_stroke$p.value)
}
df_univar_imp_deces = data.frame("Name" = name,
                           "HR" = HR_deces,
                           "p" = p_deces)
df_univar_imp_deces$signif = ifelse(df_univar_imp_deces$p<=0.05,1,0)
df_univar_imp_chd = data.frame("Name" = name,
                           "HR" = HR_chd,
                           "p" = p_chd)
df_univar_imp_chd$signif = ifelse(df_univar_imp_chd$p<=0.05,1,0)
df_univar_imp_stroke = data.frame("Name" = name,
                           "HR" = HR_stroke,
                           "p" = p_stroke)

df_univar_imp_stroke$signif = ifelse(df_univar_imp_stroke$p<=0.05,1,0)
df_univar_imp_deces
df_univar_imp_chd
df_univar_imp_stroke
```
```{r}
cox_univar_deces_imp = df_univar_imp_deces$Name[df_univar_imp_deces$signif == 1]
cox_univar_chd_imp = df_univar_imp_chd$Name[df_univar_imp_chd$signif == 1]
cox_univar_stroke_imp = df_univar_imp_stroke$Name[df_univar_imp_stroke$signif == 1]
```

# 3. Modèles multivariés
## Modèle 1

```{r}
HR_deces = c()
p_deces = c()
HR_chd = c()
p_chd= c()
HR_stroke = c()
p_stroke= c()
name = c()
for(param in c(stiffness_anat,stiffness_dyna)){
  list_deces = list()
  list_chd = list()
  list_stroke = list()
  name = c(name, as.character(df_echotracking$Tidy[df_echotracking$Missy == param]))
for(i in 1:data_mice$m){
   d = complete(data_mice,i)
  for(j in colnames(d)){
   if(!(j %in% no_scale_imp)){
    d[,j]= (d[,j]-mean(d[,j]))/sd(d[,j])
   }
  }
  f_deces = as.formula(paste("Surv(time_to_deces,deces)~",param, "+ age0 + sexe"))
  f_chd = as.formula(paste("Surv(time_to_chd,chd)~",param, "+ age0 + sexe"))
  f_stroke = as.formula(paste("Surv(time_to_stroke,stroke)~",param, "+ age0 + sexe"))
  list_deces[[i]] = coxph(f_deces, data = d)
  list_chd[[i]] = coxph(f_chd, data = d)
  list_stroke[[i]] = coxph(f_stroke, data = d)
}
list_deces = as.mira(list_deces)
list_chd = as.mira(list_chd)
list_stroke = as.mira(list_stroke)
pool_deces = pool(list_deces)
pool_chd = pool(list_chd)
pool_stroke = pool(list_stroke)
sum_pool_deces = summary(pool_deces)
sum_pool_chd = summary(pool_chd)
sum_pool_stroke = summary(pool_stroke)
HR_deces = c(HR_deces, exp(sum_pool_deces$estimate[1]))
HR_chd = c(HR_chd, exp(sum_pool_chd$estimate[1]))
HR_stroke = c(HR_stroke, exp(sum_pool_stroke$estimate[1]))
p_deces = c(p_deces, sum_pool_deces$p.value[1])
p_chd = c(p_chd, sum_pool_chd$p.value[1])
p_stroke = c(p_stroke, sum_pool_stroke$p.value[1])
  }


df_m1_imp_deces = data.frame("Name" = name,
                            "HR" = HR_deces,
                            "p" = p_deces)
df_m1_imp_deces$signif = ifelse(df_m1_imp_deces$p<=0.05,1,0)
df_m1_imp_chd = data.frame("Name" = name,
                            "HR" = HR_chd,
                            "p" = p_chd)
df_m1_imp_chd$signif = ifelse(df_m1_imp_chd$p<=0.05,1,0)
df_m1_imp_stroke = data.frame("Name" = name,
                            "HR" = HR_stroke,
                            "p" = p_stroke)
df_m1_imp_stroke$signif = ifelse(df_m1_imp_stroke$p<=0.05,1,0)
df_m1_imp_deces
df_m1_imp_chd
df_m1_imp_stroke
```


## Modèle 2

```{r}
HR_deces = c()
p_deces = c()
HR_chd = c()
p_chd= c()
HR_stroke = c()
p_stroke= c()
name = c()
for(param in c(stiffness_anat,stiffness_dyna)){
  list_deces = list()
  list_chd = list()
  list_stroke = list()
  name = c(name, as.character(df_echotracking$Tidy[df_echotracking$Missy == param]))
for(i in 1:data_mice$m){
   d = complete(data_mice,i)
for(j in colnames(d)){
   if(!(j %in% no_scale_imp)){
    d[,j]= (d[,j]-mean(d[,j]))/sd(d[,j])
   }
  }
  f_deces = as.formula(paste("Surv(time_to_deces,deces)~",param, "+ age0 + sexe + qm16 + qm10+ bmi"))
  f_chd = as.formula(paste("Surv(time_to_chd,chd)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi"))
  f_stroke = as.formula(paste("Surv(time_to_stroke,stroke)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi"))
  list_deces[[i]] = coxph(f_deces, data = d)
  list_chd[[i]] = coxph(f_chd, data = d)
  list_stroke[[i]] = coxph(f_stroke, d)
}
list_deces = as.mira(list_deces)
list_chd = as.mira(list_chd)
list_stroke = as.mira(list_stroke)
pool_deces = pool(list_deces)
pool_chd = pool(list_chd)
pool_stroke = pool(list_stroke)
sum_pool_deces = summary(pool_deces)
sum_pool_chd = summary(pool_chd)
sum_pool_stroke = summary(pool_stroke) 
HR_deces = c(HR_deces, exp(sum_pool_deces$estimate[1]))
HR_chd = c(HR_chd, exp(sum_pool_chd$estimate[1]))
HR_stroke = c(HR_stroke, exp(sum_pool_stroke$estimate[1]))
p_deces = c(p_deces, sum_pool_deces$p.value[1])
p_chd = c(p_chd, sum_pool_chd$p.value[1])
p_stroke = c(p_stroke, sum_pool_stroke$p.value[1])
  }


df_m2_imp_deces = data.frame("Name" = name,
                            "HR" = HR_deces,
                            "p" = p_deces)
df_m2_imp_deces$signif = ifelse(df_m2_imp_deces$p<=0.05,1,0)
df_m2_imp_chd = data.frame("Name" = name,
                            "HR" = HR_chd,
                            "p" = p_chd)
df_m2_imp_chd$signif = ifelse(df_m2_imp_chd$p<=0.05,1,0)
df_m2_imp_stroke = data.frame("Name" = name,
                            "HR" = HR_stroke,
                            "p" = p_stroke)
df_m2_imp_stroke$signif = ifelse(df_m2_imp_stroke$p<=0.05,1,0)
df_m2_imp_deces
df_m2_imp_chd
df_m2_imp_stroke
```

## Modèle 3
```{r}
HR_deces = c()
p_deces = c()
HR_chd = c()
p_chd= c()
HR_stroke = c()
p_stroke= c()
name = c()
for(param in c(stiffness_anat,stiffness_dyna)){
  list_deces = list()
  list_chd = list()
  list_stroke = list()
  name = c(name, as.character(df_echotracking$Tidy[df_echotracking$Missy == param]))
for(i in 1:data_mice$m){
   d = complete(data_mice,i)
for(j in colnames(d)){
   if(!(j %in% no_scale_imp)){
    d[,j]= (d[,j]-mean(d[,j]))/sd(d[,j])
   }
  }
  f_deces = as.formula(paste("Surv(time_to_deces,deces)~",param, "+ age0 + sexe + qm16 + qm10+ bmi + diab + bio10 + trb17 + ldl"))
  f_chd = as.formula(paste("Surv(time_to_chd,chd)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi+ diab + bio10 + trb17 + ldl"))
  f_stroke = as.formula(paste("Surv(time_to_stroke,stroke)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi+ diab + bio10 + trb17 + ldl"))
  list_deces[[i]] = coxph(f_deces, data = d)
  list_chd[[i]] = coxph(f_chd, data = d)
  list_stroke[[i]] = coxph(f_stroke, data = d)
}
list_deces = as.mira(list_deces)
list_chd = as.mira(list_chd)
list_stroke = as.mira(list_stroke)
pool_deces = pool(list_deces)
pool_chd = pool(list_chd)
pool_stroke = pool(list_stroke)
sum_pool_deces = summary(pool_deces)
sum_pool_chd = summary(pool_chd)
sum_pool_stroke = summary(pool_stroke) 
HR_deces = c(HR_deces, exp(sum_pool_deces$estimate[1]))
HR_chd = c(HR_chd, exp(sum_pool_chd$estimate[1]))
HR_stroke = c(HR_stroke, exp(sum_pool_stroke$estimate[1]))
p_deces = c(p_deces, sum_pool_deces$p.value[1])
p_chd = c(p_chd, sum_pool_chd$p.value[1])
p_stroke = c(p_stroke, sum_pool_stroke$p.value[1])
  }


df_m3_imp_deces = data.frame("Name" = name,
                            "HR" = HR_deces,
                            "p" = p_deces)
df_m3_imp_deces$signif = ifelse(df_m3_imp_deces$p<=0.05,1,0)
df_m3_imp_chd = data.frame("Name" = name,
                            "HR" = HR_chd,
                            "p" = p_chd)
df_m3_imp_chd$signif = ifelse(df_m3_imp_chd$p<=0.05,1,0)
df_m3_imp_stroke = data.frame("Name" = name,
                            "HR" = HR_stroke,
                            "p" = p_stroke)
df_m3_imp_stroke$signif = ifelse(df_m3_imp_stroke$p<=0.05,1,0)
df_m3_imp_deces
df_m3_imp_chd
df_m3_imp_stroke
```


## Modèle 4 

```{r}
HR_deces = c()
p_deces = c()
HR_chd = c()
p_chd= c()
HR_stroke = c()
p_stroke= c()
name = c()
for(param in c(stiffness_anat,stiffness_dyna)){
  list_deces = list()
  list_chd = list()
  list_stroke = list()
  name = c(name, as.character(df_echotracking$Tidy[df_echotracking$Missy == param]))
for(i in 1:data_mice$m){
   d = complete(data_mice,i)
for(j in colnames(d)){
   if(!(j %in% no_scale_imp)){
    d[,j]= (d[,j]-mean(d[,j]))/sd(d[,j])
   }
  }
  f_deces = as.formula(paste("Surv(time_to_deces,deces)~",param, "+ age0 + sexe + qm16 + qm10+ bmi + diab + bio10 + trb17 + ldl + mbp"))
  f_chd = as.formula(paste("Surv(time_to_chd,chd)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi+ diab + bio10 + trb17 + ldl + mbp"))
  f_stroke = as.formula(paste("Surv(time_to_stroke,stroke)~",param, "+ age0 + sexe+ qm16 + qm10 + bmi+ diab + bio10 + trb17 + ldl +mbp"))
  list_deces[[i]] = coxph(f_deces, data = d)
  list_chd[[i]] = coxph(f_chd, data = d)
  list_stroke[[i]] = coxph(f_stroke, d)
}
list_deces = as.mira(list_deces)
list_chd = as.mira(list_chd)
list_stroke = as.mira(list_stroke)
pool_deces = pool(list_deces)
pool_chd = pool(list_chd)
pool_stroke = pool(list_stroke)
sum_pool_deces = summary(pool_deces)
sum_pool_chd = summary(pool_chd)
sum_pool_stroke = summary(pool_stroke) 
HR_deces = c(HR_deces, exp(sum_pool_deces$estimate[1]))
HR_chd = c(HR_chd, exp(sum_pool_chd$estimate[1]))
HR_stroke = c(HR_stroke, exp(sum_pool_stroke$estimate[1]))
p_deces = c(p_deces, sum_pool_deces$p.value[1])
p_chd = c(p_chd, sum_pool_chd$p.value[1])
p_stroke = c(p_stroke, sum_pool_stroke$p.value[1])
  }


df_m4_imp_deces = data.frame("Name" = name,
                            "HR" = HR_deces,
                            "p" = p_deces)
df_m4_imp_deces$signif = ifelse(df_m4_imp_deces$p<=0.05,1,0)
df_m4_imp_chd = data.frame("Name" = name,
                            "HR" = HR_chd,
                            "p" = p_chd)
df_m4_imp_chd$signif = ifelse(df_m4_imp_chd$p<=0.05,1,0)
df_m4_imp_stroke = data.frame("Name" = name,
                            "HR" = HR_stroke,
                            "p" = p_stroke)
df_m4_imp_stroke$signif = ifelse(df_m4_imp_stroke$p<=0.05,1,0)
df_m4_imp_deces
df_m4_imp_chd
df_m4_imp_stroke
```

#4. Tableau comparatifs complete case et données imputées

```{r}
compar_univar_deces = cbind(as.character(df_univar_imp_deces$Name),
                            round(df_univar_imp_deces$HR,2),
                            ifelse(df_univar_imp_deces$p<0.001,"<0.001",signif(df_univar_imp_deces$p,3)),
                            round(list_univar_tos_std$deces$HR,2),
                            ifelse(list_univar_tos_std$deces$p.value<0.001,"<0.001",signif(list_univar_tos_std$deces$p.value,3))
)
compar_univar_deces 
```

```{r}
kable(compar_univar_deces, col.names = c("","HR","p","HR","p")) %>% kable_styling(full_width = F) %>% add_header_above(c(" " = 1, "Imputed Data" = 2, "Complete case" = 2))
```


```{r}
compar_univar_chd = cbind(as.character(df_univar_imp_chd$Name),
                            round(df_univar_imp_chd$HR,2),
                            ifelse(df_univar_imp_chd$p<0.001,"<0.001",signif(df_univar_imp_chd$p,3)),
                            round(list_univar_tos_std$chd$HR,2),
                            ifelse(list_univar_tos_std$chd$p.value<0.001,"<0.001",signif(list_univar_tos_std$chd$p.value,3))
)
compar_univar_chd 
```

```{r}
kable(compar_univar_chd, col.names = c("","HR","p","HR","p")) %>% kable_styling(full_width = F) %>% add_header_above(c(" " = 1, "Imputed Data" = 2, "Complete case" = 2))
```

```{r}
compar_univar_stroke = cbind(as.character(df_univar_imp_stroke$Name),
                            round(df_univar_imp_stroke$HR,2),
                            ifelse(df_univar_imp_stroke$p<0.001,"<0.001",signif(df_univar_imp_stroke$p,3)),
                            round(list_univar_tos_std$stroke$HR,2),
                            ifelse(list_univar_tos_std$stroke$p.value<0.001,"<0.001",signif(list_univar_tos_std$stroke$p.value,3))
)
compar_univar_stroke 
```

```{r}
kable(compar_univar_stroke, col.names = c("","HR","p","HR","p")) %>% kable_styling(full_width = F) %>% add_header_above(c(" " = 1, "Imputed Data" = 2, "Complete case" = 2))
```





