---
title: "Power Calculation"
output: html_notebook
---
# 1. Fonctions
```{r}
sample_size_calc = function(alpha = 0.05, power = 0.8, sd, HR, p.event.overall){
  
  num = (qnorm(1-alpha/2) + qnorm(power))^2
  den = sd^2 * (log(HR))^2
  D = num/den
  N = ceil(D/p.event.overall)
  
  return(list("D" = D, "N"=N))
}
```
```{r}
sample_size_calc(sd = 0.63, HR = 0.7, p.event.overall = 0.025)
```

```{r}
sample_size_calc1 = function(alpha = 0.05, power = 0.8, sd, HR, p.event.overall, graph = F, kable_latex = F){
  
  num = (qnorm(1-alpha/2) + qnorm(power))^2
  den = sd^2 * (log(HR))^2
  D = num/den
  N =ceil(D/p.event.overall)
  
  if(graph == T){plot(x = HR, y = N)}
  
  df = data.frame("HR" = HR, "D" = D, "N" = N)
  
  if(kable_latex == T){
    return(kable(df, "latex"))
  }
  else{
    return(df)
  }
}
```
```{r}
sample_size_calc1(sd = 0.63, HR = 0.7, p.event.overall = 0.025)
```

```{r}
sample_size_calc2 = function(alpha = 0.05, power = 0.8, sd, HR, p.event.overall, kable_latex = F){
  
  i=1
  df_list = list()
  for(p in p.event.overall){
    num = (qnorm(1-alpha/2) + qnorm(power))^2
    den = sd^2 * (log(HR))^2
    D = num/den
    N = ceil(D/p)
    df_list[[i]] = data.frame(HR, N)
    colnames(df_list[[i]]) = c("HR", paste0("N_",p))
    i = i+1
  }
  rm(i)
  res = Reduce(inner_join,df_list)
  if(kable_latex == T){
    return(kable(res, "latex"))
  }
  else{
        return(res)
  }
}
```

```{r}
sample_size_calc2(sd = 1.4, HR = c(1.1,1.2,1.4), p.event.overall = c(0.02,0.05,0.1))
```

```{r}
p.event = function(evt, dt, r = 3){
  return(round(length(which(dt[,evt] == 1))/dim(dt)[1],r))
}
```


# 2. Application: tableaux de valeurs


```{r}
res2 = c()
for(param in c(stiffness_anat[-3])){
  res= c()
for(p in c(p.deces,p.chd,p.stroke)){
  HR = sample_size_calc2(sd = sd(data4[,param]), HR = seq(0.9,2.5,0.1)[-2] , p.event.overall = p)[,1]
  tmp = sample_size_calc2(sd = sd(data4[,param]), HR = seq(0.9,2.5,0.1)[-2] , p.event.overall = p)[,2]
  res = cbind(res,tmp)
}
colnames(res) = c("deces","chd","stroke")
#res = cbind(HR,res)
res2 = cbind(res2,res)
}
res2 = cbind(HR,res2)
colnames(res2) = c("", rep(c("Death","CHD","Stroke"),5))
kable(res2)%>% kable_styling(full_width = T) %>% add_header_above(c("HR" = 1, "IMT" = 3, "Diast. Diam" = 3, "Compliance" =3, "WCSA"= 3, "CWS"= 3 ))
```

```{r}
res2 = c()
for(param in c(stiffness_dyna)){
  res= c()
for(p in c(p.deces,p.chd,p.stroke)){
  HR = sample_size_calc2(sd = sd(data4[,param]), HR = seq(0.9,2.5,0.1)[-2] , p.event.overall = p)[,1]
  tmp = sample_size_calc2(sd = sd(data4[,param]), HR = seq(0.9,2.5,0.1)[-2] , p.event.overall = p)[,2]
  res = cbind(res,tmp)
}
colnames(res) = c("deces","chd","stroke")
#res = cbind(HR,res)
res2 = cbind(res2,res)
}
res2 = cbind(HR,res2)
colnames(res2) = c("", rep(c("Death","CHD","Stroke"),7))
kable(res2)%>% kable_styling(full_width = T) %>% add_header_above(c("HR" = 1, "Stiffness" = 3, "Young's Modulus" = 3, "Coef. Dist." =3, "Distension"= 3, "Dist. rate"= 3, "Carotid PWV" = 3 , "Central Pulse pressure" = 3))
```

```{r}
p.deces = p.event("deces", data4)
p.chd = p.event("chd", data4)
p.stroke = p.event("stroke", data4)
p_4 = c(p.deces,p.chd)
sample_size_d4 = list()
i = 1
for(param in c(stiffness_anat,stiffness_dyna)){
  if(!(is.factor(data4[,param]))){
    sd = sd(data4[,param], na.rm = T)
  sample_size_d4[[i]] = sample_size_calc2(sd = sd, HR = seq(0.9,2.5,0.1)[-2] , p.event.overall = p_4)
  i = i+1
  }
  
}
names(sample_size_d4) = c(stiffness_anat,stiffness_dyna)[-3]
```

```{r}
tab_sample_size = c()
for(param in c(stiffness_anat[-3],stiffness_dyna)){
  tmp = 
}
```


# Graphes

```{r}
plot_sample_size = function(param, s = 1){
    print(ggplot(list_sample_size[[param]]) + 
  geom_line(aes(x = HR, y = N_0.025, col = "Death"),size = s) + geom_line(aes(x = HR, y = N_0.024,col = "CHD"),size = s)  + geom_line(aes(x = HR, y = N_0.017,col = "TDR"),size = s)+ geom_line(aes(x = HR, y = N_0.011,col = "Stroke"),size = s)+ geom_line(aes(x = HR, y = N_0.003, col = "AOMI"),size = s)+ 
  scale_color_manual(values = c('Death' = 'red','CHD' = 'darkblue', 'TDR' = 'orange', 'Stroke' = 'purple','AOMI' = 'steelblue')) +labs(color = 'Events')  +
  ggtitle(paste("Sample size for the",param)) + ylab("N"))
  
}
```
```{r}
for(p in var_et_jpe_inf){
  plot_sample_size(p)
}
```






