---
title: "R Notebook"
output: html_document
---

# 1. Tests


```{r}
i = 0
test_univar_deces = c()
test_univar_chd = c()
for(var in echotracking_clean){
  i = i+1
  if(is.numeric(data2[,var])){
    
    test_deces = t.test(data2[,var]~data2$deces)
    test_chd = t.test(data2[,var]~data2$chd)
     if(test_deces$p.value <= 0.05){
       test_univar_deces = c(test_univar_deces,var)
     }
     if(test_chd$p.value <= 0.05){
       test_univar_chd = c(test_univar_chd,var)
     }

    }
  
  else{
    test_deces = chisq.test(data2[,var],data2$deces)
    test_chd = chisq.test(data2[,var], data2$chd)
     if(test_deces$p.value <= 0.05){
       test_univar_deces = c(test_univar_deces,var)
     }
     if(test_chd$p.value <= 0.05){
       test_univar_chd = c(test_univar_chd,var)
     }
  }

}
```
```{r}
length(test_univar_deces)
length(test_univar_chd)
```


# 2. Tableau récap (table1 paper1)

```{r}
IncrementalTable_all = c() 
for(i in echotracking_clean) {
  
  # Variables numériques
  
  if(is.numeric(data2[,i]))
    
  {
    
    ## Calcul des moyennes et des écarts types
    mean_ov = data2[,i] %>% (function(x) round(mean(x,na.rm = T),digits = 2)) 
    sd_ov = data2[,i] %>% (function(x) round(sd(x,na.rm = T),digits = 2))
    
    mean_deces0 = data2[data2$deces == 0,i] %>% (function(x) round(mean(x,na.rm = T),digits = 2)) 
    sd_deces0 = data2[data2$deces == 0,i] %>% (function(x) round(sd(x,na.rm = T),digits = 2))
    
    mean_deces1 = data2[data2$deces == 1,i] %>% (function(x) round(mean(x,na.rm = T),digits = 2)) 
    sd_deces1 = data2[data2$deces == 1,i] %>% (function(x) round(sd(x,na.rm = T),digits = 2))
    
    mean_chd0 = data2[data2$chd == 0,i] %>% (function(x) round(mean(x,na.rm = T),digits = 2)) 
    sd_chd0 = data2[data2$chd == 0,i] %>% (function(x) round(sd(x,na.rm = T),digits = 2))
    
    mean_chd1 = data2[data2$chd == 1,i] %>% (function(x) round(mean(x,na.rm = T),digits = 2)) 
    sd_chd1 = data2[data2$chd == 1,i] %>% (function(x) round(sd(x,na.rm = T),digits = 2))
    
    ## Construction des noms
    name = paste0(i) 
    
    ## Clacul nombre de NA
    mis = sum(is.na(data2[,i]))
    
    ## Tests de Student
    test_deces = t.test(data2[,i]~data2$deces)
    test_chd = t.test(data2[,i]~data2$chd)

    
    increment = matrix(c(name,
                         unlist(mean_ov),
                         paste0(prefix="(",unlist(sd_ov), postfix=")"),
                         unlist(mean_deces0),
                         paste0(prefix="(",unlist(sd_deces0), postfix=")"),
                         unlist(mean_deces1), 
                         paste0(prefix="(",unlist(sd_deces1), postfix=")"),
                         unlist(mean_chd0),
                         paste0(prefix="(",unlist(sd_chd0), postfix=")"),
                         unlist(mean_chd1), 
                         paste0(prefix="(",unlist(sd_chd1), postfix=")"),
                         signif(test_deces$p.value,2),
                         signif(test_chd$p.value,2),
                         mis), 
                       ncol = 14)
  } 
  
  # Variables catégorielles
  
  else {
    
    ## Calcul des moyennes et des écarts types
    ## On stock dans mean le nb d'obs par classe et dans sd la prop d'obs de chaque classe 
    mean_ov = data2[,i] %>% (function(x) table(x, useNA = "n"))
    sd_ov = data2[,i] %>% (function(x) round(prop.table(table(x,useNA = "n")),digits=3))
    
    mean_deces0 = data2[data2$deces == 0,i] %>% (function(x) table(x, useNA = "n"))
    sd_deces0 = data2[data2$deces == 0,i] %>% (function(x) round(prop.table(table(x,useNA = "n")),digits=3))
    
    mean_deces1 = data2[data2$deces == 1,i] %>% (function(x) table(x, useNA = "n"))
    sd_deces1 = data2[data2$deces == 1,i] %>% (function(x) round(prop.table(table(x,useNA = "n")),digits=3))
    
    mean_chd0 = data2[data2$chd == 0,i] %>% (function(x) table(x, useNA = "n"))
    sd_chd0 = data2[data2$chd == 0,i] %>% (function(x) round(prop.table(table(x,useNA = "n")),digits=3))
    
    mean_chd1 = data2[data2$chd == 1,i] %>% (function(x) table(x, useNA = "n"))
    sd_chd1 = data2[data2$chd == 1,i] %>% (function(x) round(prop.table(table(x,useNA = "n")),digits=3))
    
    
    ## Tests du chi^2
    test_deces = chisq.test(data2[,i], data2$deces)
    test_chd = chisq.test(data2[,i], data2$chd)
    
    # Si pas de NA on ordonne les classes par nb decroissant d'obs
    # if(sum(is.na(data2[,i])) == 0) { 
    #   mean_ov = sort(mean_ov,decreasing = T)
    #   mean_deces0 = sort(mean_deces0,decreasing = T)
    #   mean_deces1 = sort(mean_deces1,decreasing = T)
    #   mean_chd0 = sort(mean_chd0,decreasing = T)
    #   mean_chd1 = sort(mean_chd1,decreasing = T)
    #   }

    # Si pas de NA on ordonne les classes par prop decroissante d'obs
    # if(sum(is.na(data2[,i])) == 0) { 
    #   sd_ov = sort(sd_ov,decreasing = T)
    #   sd_deces0 = sort(sd_deces0,decreasing = T)
    #   sd_deces1 = sort(sd_deces1,decreasing = T)
    #   sd_chd0 = sort(sd_chd0,decreasing = T)
    #   sd_chd1 = sort(sd_chd1,decreasing = T)
    #   }
    
    # Nombre de NA
    mis = sum(is.na(data2[,i]))
    
    # On change les nom des classes
    #data2[,i] = factor(data2[,i], levels = names(mean)) 
    
    # On transforme les obs par classe, stockées dans mean, en matrice : permet d'avoir les classes en lignes pluôt qu'en colonnes 
    mean_ov = as.matrix(mean_ov)
    mean_deces0 = as.matrix(mean_deces0)
    mean_deces1 = as.matrix(mean_deces1)
    mean_chd0 = as.matrix(mean_chd0)
    mean_chd1 = as.matrix(mean_chd1)
    
    
    # on stock dans name le nom des classes (correspond aux noms des lignes de la matrice mean)
    name = matrix(rownames(mean_ov),nrow = length(mean_ov))
    
    # On stock le tout dans une matrice increment
    increment = matrix(c(name,
                         unlist(mean_ov),
                         paste0(prefix="(",unlist(sd_ov)*100, postfix=")"),
                         unlist(mean_deces0),
                         paste0(prefix="(",unlist(sd_deces0)*100, postfix=")"),
                         unlist(mean_deces1),
                         paste0(prefix="(",unlist(sd_deces1)*100, postfix=")"),
                         unlist(mean_chd0),
                         paste0(prefix="(",unlist(sd_chd0)*100, postfix=")"),
                         unlist(mean_chd1),
                         paste0(prefix="(",unlist(sd_chd1)*100, postfix=")"),
                         rep("",nrow(mean_chd1)),
                         rep("",nrow(mean_chd1)),
                         rep("",nrow(mean_chd1))
                         )
                       , ncol = 14)
    increment = rbind(c(i,
                        matrix("",nrow = 1,ncol = 10),
                        signif(test_deces$p.value,2),
                        signif(test_chd$p.value,2),
                        mis),
                      increment)
  }
  
IncrementalTable_all = rbind(IncrementalTable_all,increment)
}

rm(list = c("i","mean_ov","mean_deces0","mean_deces1","mean_chd0","mean_chd1","sd_ov","sd_deces0","sd_deces1","sd_chd0","sd_chd1"))
```
```{r}
colnames(IncrementalTable_all) = rep(" ",ncol(IncrementalTable_all))
```
```{r}
IncrementalTable_all[,1] =  c("Basale cardiac rate", 
                                    "Diastolic outer diameter (bm)", 
                                    "Itima Media Thickness",
                                    "Distension", 
                                    "Pulse Wave Velocity", 
                                    "Central Pulse Pressure",
                                    "Distension Rate (Mean)",
                                    "RR interval (Mean)", 
                                    "Low frequency Distension Rate (t)", 
                                    "High frequency Distension rate (t)", 
                                    "High frequency Distensin Rate (c)", 
                                    "Low frequency RR interval (t)", 
                                    "High frequency RR interval (t)", 
                                    "High frequency RR interval (c)",
                                    "Respiratory rate",
                                    "Low frequency COH (Mean)",
                                    "Low frequency Gain (Mean)",
                                    "High frequency COH (Mean) (c)",
                                    "High frequency Gain (Mean) (c)",
                                    "High frequency COH (Mean) (t)",
                                    "High frequency Gain (Mean) (t)",
                                    "Distension (Mean)",
                                    "Circumferential Wall Stress",
                                    "Coefficient of distensibility",
                                    "Cross Sectional Compliance",
                                    "Wall Cross Sectionnal Area",
                                    "Young Module",
                                    "Presence of plaques",
                                    "No",
                                    "Yes",
                                    "Gain (log)",
                                    "Young Module (log)",
                                    "Diastolic outer diameter (bm*1000)",
                                    "Stiffness")
```


```{r}
kable(IncrementalTable_all, longtable = T, caption = "table 1, test univariés") %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "N = 9947" = 2, "No : N = 9703" = 2, "Yes : N = 244" = 2, "No : N = 9712" = 2, "Yes : N = 235" = 2, " " = 3)) %>%
  add_header_above(c(" " = 1, "Overall" = 2, "Death" = 4, "CHD" = 4, "Death" = 1, "CHD" = 1, " " = 1)) %>%
  add_header_above(c(" " = 1, "Mean (sd) or N (%)" = 10, "pvalues" = 2, "NA" = 1)) %>%
kable_styling(latex_options = c("repeat_header"))
```


```{r}
length(test_univar_deces)
length(test_univar_chd)
```
```{r}
test_univar = unique(c(test_univar_chd,test_univar_deces))
length(test_univar)
```



